---
title: "R summary"
author: "Lan Lin"
date: '2022-07-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### What your current thoughts are in terms of using R for data science - do you think you'll continue to use R going forward?  Why or why not?
The cool thing that impressed me the most is the R Shiny. Shiny is an R package that enables building interactive web applications that can execute R code on the backend. With Shiny, I can host standalone applications on a webpage, embed interactive charts in R Markdown documents, or build dashboards. Our lab is interested in using DNA methylation profiling to build a melanocytic tumor diagnostic classifier for precision medicine. Learning R Shiny ecouges me to make our model as a R Shiny application to help people predict diseases. 

### What things are you going to do differently in practice now that you've had this course?
I have a background in Biology, and I used the COVID-19 API for my project 1. I will choose a different database to help me explore other fields if I can take this course again.

### what areas of statistics/data science are you thinking about exploring further?
I don't have a solid foundation in fitting models. I will read more books on theory or join a reading group that goes through different modeling techniques.